<?php
declare(strict_types=1);

// Screenshot SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ScreenshotUtility::setRegistrar(function (ScreenshotUtility $u): void {
    $u->clean = [ScreenshotClean::class, 'call'];
    $u->done = [ScreenshotDone::class, 'call'];
    $u->make_error = [ScreenshotMakeError::class, 'call'];
    $u->feature_add = [ScreenshotFeatureAdd::class, 'call'];
    $u->feature_hook = [ScreenshotFeatureHook::class, 'call'];
    $u->feature_init = [ScreenshotFeatureInit::class, 'call'];
    $u->fetcher = [ScreenshotFetcher::class, 'call'];
    $u->make_fetch_def = [ScreenshotMakeFetchDef::class, 'call'];
    $u->make_context = [ScreenshotMakeContext::class, 'call'];
    $u->make_options = [ScreenshotMakeOptions::class, 'call'];
    $u->make_request = [ScreenshotMakeRequest::class, 'call'];
    $u->make_response = [ScreenshotMakeResponse::class, 'call'];
    $u->make_result = [ScreenshotMakeResult::class, 'call'];
    $u->make_point = [ScreenshotMakePoint::class, 'call'];
    $u->make_spec = [ScreenshotMakeSpec::class, 'call'];
    $u->make_url = [ScreenshotMakeUrl::class, 'call'];
    $u->param = [ScreenshotParam::class, 'call'];
    $u->prepare_auth = [ScreenshotPrepareAuth::class, 'call'];
    $u->prepare_body = [ScreenshotPrepareBody::class, 'call'];
    $u->prepare_headers = [ScreenshotPrepareHeaders::class, 'call'];
    $u->prepare_method = [ScreenshotPrepareMethod::class, 'call'];
    $u->prepare_params = [ScreenshotPrepareParams::class, 'call'];
    $u->prepare_path = [ScreenshotPreparePath::class, 'call'];
    $u->prepare_query = [ScreenshotPrepareQuery::class, 'call'];
    $u->graphql_body = [ScreenshotGraphql::class, 'body'];
    $u->graphql_errors = [ScreenshotGraphql::class, 'errors'];
    $u->result_basic = [ScreenshotResultBasic::class, 'call'];
    $u->result_body = [ScreenshotResultBody::class, 'call'];
    $u->result_headers = [ScreenshotResultHeaders::class, 'call'];
    $u->transform_request = [ScreenshotTransformRequest::class, 'call'];
    $u->transform_response = [ScreenshotTransformResponse::class, 'call'];
});
